version: '2'

services:
  node.od-backend:
    container_name: od-backend-node
    image: node:12.13.0-alpine
    working_dir: /app
    ports:
      - 4330:4330
    volumes:
      - ./:/app
      - od-node_modules-test:/app/node_modules
      - od-dist-test:/app/dist
    environment:
      - ROOT_PATH=/app
      - PORT=4330
      - JWT_SECRET=foobar
      - PASS_HASH_SALT=342dsfs34
      - DNN_FACE_URL=http://od-backend-image_face_detector:5001
      - DNN_NSFW_URL=http://od-backend-adult-image-detector:9191
      - DB_HOST=od-backend-postgres-test
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASS=mysecretpassword
      - DB_NAME=od-test
      - NODE_ENV=testing
    networks:
      - od-network-test
    command: sh -c "npm i && npm run typeorm:run && npm run build && npm run start:prod"

  postgres-test.od-backend:
    container_name: od-backend-postgres-test
    image: mdillon/postgis:11-alpine
    environment:
      POSTGRES_DB: od-test
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 4333:5432
    volumes:
      - od-postgres-test:/var/lib/postgresql/data
    networks:
      - od-network-test

  image_face_detector.od-backend:
    container_name: od-backend-image_face_detector
    image: grinat0/image_face_detector:0.0.3
    networks:
      - od-network-test

  adult-image-detector.od-backend:
    container_name: od-backend-adult-image-detector
    image: opendating/adult-image-detector
    networks:
      - od-network-test

volumes:
  od-postgres-test:
  od-node_modules-test:
  od-dist-test:

networks:
  od-network-test:
