version: '2'

services:
  postgres.od-backend:
    container_name: od-backend-postgres
    image: mdillon/postgis:11-alpine
    environment:
      POSTGRES_DB: od
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 4332:5432
    volumes:
      - od-postgres-dev:/var/lib/postgresql/data
    networks:
      - od-network

  adminer.od-backend:
    image: adminer:4.7.5-standalone
    ports:
      - 4301:8080
    networks:
      - od-network

  image_face_detector.od-backend:
    container_name: od-backend-image_face_detector
    image: grinat0/image_face_detector:0.0.3
    ports:
      - 5001:5001
    networks:
      - od-network

  adult-image-detector.od-backend:
    container_name: od-backend-adult-image-detector
    image: opendating/adult-image-detector
    ports:
      - 9191:9191
    networks:
      - od-network

volumes:
  od-postgres-dev:

networks:
  od-network:
